# Generated by Django 6.0 on 2025-12-05 11:46
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def add_init_wallets(apps, schema_editor):
    Wallet = apps.get_model("transfer", "Wallet")

    initial_wallets = {
        "tech_admin": Decimal("0"),
        "user_1": Decimal("1000"),
        "user_2": Decimal("1000"),
    }

    existing_owners = set(
        Wallet.objects.filter(owner__in=initial_wallets.keys())
        .values_list("owner", flat=True)
    )

    wallets_to_create = [
        Wallet(owner=owner, balance=balance)
        for owner, balance in initial_wallets.items()
        if owner not in existing_owners
    ]

    if wallets_to_create:
        Wallet.objects.bulk_create(wallets_to_create, batch_size=10)


def add_init_wallets_reverse(apps, schema_editor):
    Wallet = apps.get_model("transfer", "Wallet")

    owners_to_delete = ("tech_admin", "user_1", "user_2")

    Wallet.objects.filter(owner__in=owners_to_delete).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency',
                 models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('u', 'u')], default='u', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_debit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status',
                 models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')],
                                  default='pending', max_length=10)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing',
                                                  to='transfer.wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming',
                                                to='transfer.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(
            add_init_wallets,
            reverse_code=add_init_wallets_reverse,
        ),
    ]
